[versions]
kotlinPlugin = "1.9.23"
sonarqubePlugin = "5.0.0.4638"

[libraries]
kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinPlugin" }
sonarqube = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref ="sonarqubePlugin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinPlugin" }
